### ISSUE TITLE
Animating without DOM/CSS

### ISSUE THREAD

**Issue by appsforartists** [WICG/animation-worklet#16]
The current proposal relies heavily on DOM APIs and CSS custom properties to send input to an animator.  How would you control (play, pause, send input to, etc.) an animator from JavaScript without serializing to/from a style map?  Is there an API (like `element.animate`) that would give JavaScript the ability to trigger an animation without touching the style map?

**Comment by majido** [comment]
I agree that we want a Javascript API to interface with animators. A JS API is more flexible. You are correct about the limitation of having our only channel be the style map in particular where the input is not really attributed to an element. We had some thinking done on this and want to have but perhaps not in v1.

**Comment by majido** [comment]
We have now switched to a model where Web-Animation APIs can be used to create/play/pause the animation. Note that one still needs to have a DOM element as a target of the effect of the animation but beyond that no other CSS/DOM ties are necessary.
