### ISSUE TITLE
Support animating all properties

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#2]
Some (eg. @birtles) have argued that we should be consistent with animations on the web and allow any property as an output property.  Eg. to avoid requiring a spec change to expand the set of animatable properties (since some browsers may move faster on that than others).

I think there's broad support for expanding the design for that, though there is debate over how exactly that should behave.

In particular, by default we'd like an error delivered to window.onerror by default whenever a not accelerated property is animated (indicating that animation can only be performed at the rate of the main thread).  Optionally a developer can indicate that they are OK with main-thread animations and disable this warning (perhaps a 3rd setting for the option in #1).

Also there is significant debate over what should happen when an Animator changes an accelerated property of one element as well as a non-accelerated property of another element.  There are two main options:

1) Synchronized: all elements update at the rate of rAF
2) Unsynchronized: the elements where only accelerated properties are changed will update off-thread, while other elements will update at least a frame behind.

Proposal: have an option for now to support either mode and build concrete demos which are better in one mode over the other.  We can pull the mode switch from the v1 API if no critical use cases end up requiring one of the modes.

**Comment by majido** [comment]
This issue was moved to w3c/css-houdini-drafts#805
