### ISSUE TITLE
Design for per-child output properties

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#3]
Some use cases rely on setting different output properties on different children, some of which create a stacking context (eg. transform) and some of which don't (eg. scrollTop).  It may be problematic to force a stacking context for all children when it's not strictly necessary.

We need to design an API that would allow output properties to be specified on a child-by-child basis.  We'll rely in specific use cases / demos to decide if this API needs to be part of the level 1 API or can be something we could add later.

**Comment by flackr** [comment]
With the required slot syntax you can have different output properties for different children.
