### ISSUE TITLE
Rename 'elements'?

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#48]
@dbaron [says](https://twitter.com/davidbaron/status/853875802940743681) we shouldn't use the term 'elements' for things which aren't actually an `HTMLElement`.  Better name?

**Comment by majido** [comment]
Here are some ideas:
 1. Use 'targets' e.g., 'targets' for getter and use AnimationTarget or EffectTarget for the class type.
2. Use 'handles' e.g., 'handles' for getter and use AnimationHandle for the class type


Web Animation uses the term "target element" but that is actually talking about an HTML element.

**Comment by majido** [comment]
The updated spec no longer references element.
