### ISSUE TITLE
Add generic mechanism for warning of non-accelerated animations

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#5]
In #2 we've talked of generating a warning/window.onerror (unless the developer has opted-out) whenever an animation cannot be accelerated and occurs on main.  @esprehn points out that this is really not a AW-specific issue, we should solve it for CSS / WebAnim generally (although in those existing cases it may need to be opt-in rather than opt-out).

**Comment by majido** [comment]
This issue was moved to w3c/css-houdini-drafts#806
