### ISSUE TITLE
Add threading motivation details to introduction

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#50]
@dbaron says it would be helpful if the spec had an introduction describing that an implementation is free to run a worklet on either the main thread or (if all the output properties are supported off-thread) a separate thread.  The idea is that this implements the same threading model as CSS animations and Web Animations (performance isolated if supported by the implementation, otherwise locked to main thread).

**Comment by majido** [comment]
Added a whole new section to spec regarding threading model.
