### ISSUE TITLE
Defaulting root to document is bad

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#51]
From Houdini F2F discussion:
For parallelism we want to avoid using the document as a root.  Perhaps if there's no root specified we should use the element itself as the implicit root?  Also fix the spring example not to use the document as the root.

**Comment by majido** [comment]
Closing we not longer have the "tree structure" that we necessary for CSS API. The new proposed web animation based scripting API allows arbitrary grouping of element (i.e., animation effects) for each animation.
