### ISSUE TITLE
Allow constructing WorkletAnimation with single KeyframeEffect.

### ISSUE THREAD

**Issue by flackr** [WICG/animation-worklet#62]
It might make sense to allow passing a single keyframe effect or an array of keyframe effects for improved consistency with animations.

i.e.
```javascript
// Implicitly constructs and uses a GroupEffect because an array of effects was given.
new WorkletAnimation('foo', [new KeyframeEffect(...), new KeyframeEffect(...)], ...);

// Passes in the single keyframe effect as the effect on the animate function.
new WorkletAnimation('foo', new KeyframeEffect(...), ...);
```

**Comment by majido** [comment]
Makes sense. I was thinking to even do the latter when an array of single element was passed in. But thinking about it more, it may be inconsistent and unexpected. 

So to clarify, the expectation in the worklet scope will be as follows:

```js
animate(timelines, effect) {
  (effect instanceof GroupEffect)  === true;
  effect.childrent[0].localTime = 0.5; 
}

// vs.
animate(timelines, effect) {
  effect instanceof GroupEffect  === false;
  effect.localTime = 0.5;  
}

**Comment by majido** [comment]
FYI, I have filed an [issue](https://github.com/w3c/web-animations/issues/191) with web-animation spec to ensure a `GroupEffect` which allows its children to be individually seeked is a reasonable addition.

**Comment by majido** [comment]
Already addressed in the spec.
