### ISSUE TITLE
Define semantic of finish/reverse/playbackRate for Worklet Animation

### ISSUE THREAD

**Issue by majido** [WICG/animation-worklet#63]
# Problem
The web animation's timing model is ["stateless"](https://w3c.github.io/web-animations/#stateless) with a notable exception of methods which change the timing properties  such as finish, or pause.

Worklet animations deviate from this timing model to enable effects that are script-driven, stateful, and runnable in a parallel worklet execution context. In particular a worklet animation output is not only dependent on its time input but also its internal state. As such the worklet animations may not necessarily be amenable to constant time seeking and direction or rate agnostic playback.

However it is desirable to make worklet animations conform to the existing [Animation](https://w3c.github.io/web-animations/#the-animation-interface) interface as much as possible. This include  `finish` method which seeks a particular time, or `reverse` method and `playbackRate` attribute that change playback rate.

# Idea 1 - allow author defined behavior
Any methods that seeks a time or changes playback rate would cause a corresponding callback to be called on the corresponding animator in the worklet context. The user script will be responsible to provide best possible mapping for the given effect.

Here is a strawman API:

``` javascript
registerAnimator('foo', class {
  animate(timeline, output) {
    if (this.finished)
     output.localTime(10);
    else 
     output.localTime(timeline.time * rate * Math.rand());  
 }
  finish() {
      this.finished = true;
  }
  reverse() { 
    console.warn("foo animation is not reversible") 
  }
  
 playbackRateChanged(rate) {
    this.playbackRate = math.abs(rate);
 }
}
 ```
Pros:
 - Authors has to work hard to "Do the Right Thing".

Cons:
- If the animation is stateless, this is too much work that could have all been done automatically. See next proposal.

# Idea 2- modify the timeline.currentTime 
We can modify the timeline.currentTime to reflect the seeked value and playbackRate. 

Pros:
 - Works fine for stateless effect.

Cons:
 - Most likely the wrong behavior for any stateful effect. We will probably still need to do callbacks as well so that the animation can adjust accordingly.  

# Conclusion
There may be an elegant solution that sits somewhere between these two proposals where we do the stateless animations are automatically doing the right thing without a lot of boilerplate without it negatively affecting the stateful animation case. But I am not sure what it is. Ideas?

Even we don't find that elegant solution. I am  inclined to go with idea 1 in particular because 1) I think it is appropriate for AnimationWorklet API to be slightly biased toward addressing the more complex stateful usecase 2) It provides more power on top of which we can add additional simplifying sugar in future.

**Comment by birtles** [comment]
In general I think it's less of an issue for `Animation`s to be stateful, and mostly an issue for their source content.

I didn't quite follow idea 2, however. Would an approach like the following work:

  Timeline time(s)
  ↓
  Some function that produces a scaled single timeline time
  ↓
  Regular `Animation` timing calculations

Is that what idea 2 is proposing? What are the use cases where that would be unsuitable?

In terms of notifying state changes, I suppose one option is a React-like [`shouldComponentUpdate`](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) API where the default implementation simply compares the values of all timelines the animation is attached to. You'd still need to call that on every frame, however, which is not good.

I'm not sure how hard this is to do with worklets but if we could instead have more of a [`setState`](https://facebook.github.io/react/docs/react-component.html#setstate) like API, i.e. something you call each time your worklet's state has changed, that would be better. Then the UA would just call `animate()` each time any of the worklet's attached timelines changed or it had been notified that the worklet's state had changed.

**Comment by majido** [comment]
This issue was moved to w3c/css-houdini-drafts#811
