### ISSUE TITLE
Mechanism to pause an animation

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#8]
For example, in the spring example it should be possible for the Animator to somehow say "I'm done now, stop invoking my `animate` function".

Maybe it should be more powerful, eg. "sleep for 5 seconds"?  Or a main-thread API to resume the Animator?

**Comment by appsforartists** [comment]
`pause` implies that there's still potential work waiting to be done.  `at rest` (or CSS transition's `end`) are better concepts for a spring that's run out of frames.

If functions were side-effect-free (#14) `return`ing a falsey value would be a good way to represent the animation has come to rest.

**Comment by flackr** [comment]
Why does returning a falsey value require side-effect-free functions? My only concern with this model is how we know when to start invoking the animation again.

Alternate suggestion, could we allow pausing the input timelines: e.g.
```js
static timelines() { return ['document']; }
animate(elementMap, timelines) {
  // do stuff
  if (done) {
    timelines[0].pause();
    // animate will no longer be called every frame, only when
    // some other input has changed at which point you can call
    // play() on the timeline to resume updating every frame.
  }
}
```

**Comment by majido** [comment]
Pausing timeline is interesting though I wouldn't probably call it pause as it implies any other animation attached to the same timeline will also get paused. It is more like "detach/attach".

**Comment by flackr** [comment]
I think each instance has its own timelines, since the registered timeline list only specifies how to construct the timelines but doesn't contain actual constructed timelines.

Another idea I had was to create a mutable timeline list that animate can add to / remove from. An animator could then remove the document timeline and readd when it was needed again.
e.g.
```js
animate(elementMap, timelines) {
  // do stuff
  if (done) {
    timelines.pop();
    // animate will no longer be called every frame, only when
    // some other input has changed.
  } else if (timelines.length == 0) {
    timelines.push(new DocumentTimeline());
  }
}

**Comment by majido** [comment]
This issue was moved to w3c/css-houdini-drafts#808
