### ISSUE TITLE
API for influencing pre-painting

### ISSUE THREAD

**Issue by RByers** [WICG/animation-worklet#9]
Browsers typically takes CSS animations / WebAnimations into account when computing pre-paint skirt data.  But (like other JS-driven animations) there may be no opportunity to do so for animations driven by AW.  The browser can't predict what the animation will look like in the future.

To fully explain the CSS animation behavior here, we should consider adding some sort of API for giving hints to the pre-paint system.

For example, in an effect where elements slide left/right onto the screen while scrolling vertically at a certain point, an AW implementation should be able to provide some sort of hint to influence when prepainting of those elements should occur.

Hopefully this is a feature we could add in the future, and just encourage people to use CSS scroll-linked animations for common cases like this today.

**Comment by flackr** [comment]
Did you have any thoughts about how you would specify this? It seems like you'd need to have bounds on the range of transforms you could apply which is tricky to do for the general case of transforms.

Alternately, we could use paint containment on an ancestor to effectively declare the region in which your animation may be visible.

**Comment by majido** [comment]
I don't think this is an issue any longer given that AnimationWorklet output is simply time values that are piped into KeyframeEffects. Each output effect has well-known bounds, and combined with a history of the time values used with that effect, it is possible then to estimate future values and use that for pre-painting. Obviously this is just an estimate but I think that should be enough for this purpose.

**Comment by majido** [comment]
My last comment explains why such pre-painting skirt is already possible since we have moved to use the web-animation model.
