### ISSUE TITLE
Attribute Delay, Iterations, Fill not working 

### ISSUE THREAD

**Issue by grvraj82** [WICG/animation-worklet#95]
`<div class="small"><img src="images/01.jpg" /></div> var smallContent = document.querySelector('.small'); new KeyframeEffect(smallContent, [{ 'opacity': 1 }, { 'opacity': 0 }], { duration: 7, fill: 'forwards', delay:5000, iterations:1 })`
In the above keyframe effect, the below mentioned options are not working:
Delay
Iterations
Fill
From html page we can only call either “play()” to start the animation or “cancel” to stop and remove the animation.
How to handle “Pause” and “Finish” animations?
Also, no documentation regarding, how to pass values to “additionalTimelines_” variable of “WorkletAnimation” class.
Need your input.
Tried Browser versions:
Google Chrome - 64.0.3282.186
IE 11
IE Edge

**Comment by majido** [comment]
This is an experimental specification. It is currently only being implemented in Chrome behind a flag so it won't work on IE or Edge.

Also, our current implementation in Chrome is only partial as you have noticed. Here is a short list of what works:
- WorkletAnimation only supports Play/Cancel. We don't have pause implemented yet.
- WorkletAnimation supports only a single timeline that can be a ScrollTimline.
- WorkletAnimation  does not support any additional options.

See this [IDL](https://codesearch.chromium.org/chromium/src/third_party/WebKit/Source/modules/animationworklet/WorkletAnimation.idl) for a sense of what is currently working.

Given this, here are some answers:

## delay, iteration and fill
I created a basic [example](https://jsfiddle.net/majidvp/weef02s9/) demo and I think delay is not working as expected in Chrome but other two are. This is a bug in our implementation in Chrome. I will report this.

## Paused and finished
> How to handle “Pause” and “Finish” animations?

Our implementation does not support finish/pause yet but you can cancel and animation which simply removes the effect.

## Additional timelines
normally you would pass these in extra parameters in WorkeltAnimation constructor but our implementation does not currently support this so basically limited to a single timeline.

**Comment by majido** [comment]
Here is the relevant chromium issues that you can follow
*  delay issue : https://bugs.chromium.org/p/chromium/issues/detail?id=824782
* duration: https://bugs.chromium.org/p/chromium/issues/detail?id=779189

Closing this issue since it is not a specification issue.
